version: "3.8"
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./backup:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: db_wp
      MARIADB_USER: user_wp
      MARIADB_PASSWORD: secret_wp
    command: bash -c "apt-get update && apt-get install -y mysql-client && mkdir -p /backup && /docker-entrypoint-initdb.d/backup-db.sh"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user_wp
      WORDPRESS_DB_PASSWORD: secret_wp
      WORDPRESS_DB_NAME: db_wp

volumes:
  db_data: {}
  wordpress_data: {}
