name: CI/CD Pipeline for WordPress

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker for gcloud
      run: gcloud auth configure-docker

    - name: Change directory to wordpress and install dependencies
      run: |
        cd wordpress
        composer install --prefer-dist --no-progress --no-interaction

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t gcr.io/$GCP_PROJECT_ID/wordpress:latest --push .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy wordpress \
          --image gcr.io/$GCP_PROJECT_ID/wordpress:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
